# Generated by Django 4.1.2 on 2022-10-29 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alldata_cpucooler_gpu_memory_outputcomputer_storage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='name',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='cpucooler',
            name='allData',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.alldata'),
        ),
        migrations.AddField(
            model_name='gpu',
            name='allData',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.alldata'),
        ),
        migrations.AddField(
            model_name='memory',
            name='allData',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.alldata'),
        ),
        migrations.AddField(
            model_name='storage',
            name='allData',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.alldata'),
        ),
        migrations.CreateModel(
            name='PowerSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('allData', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.alldata')),
            ],
        ),
    ]
