# Generated by Django 4.1.2 on 2022-10-29 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_cpu_name_cpucooler_alldata_gpu_alldata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpucooler',
            name='name',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='gpu',
            name='name',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='memory',
            name='name',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='powersupply',
            name='name',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='storage',
            name='name',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
