# Generated by Django 4.1.2 on 2022-10-29 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_cpucooler_name_gpu_name_memory_name_powersupply_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='type',
            field=models.CharField(default='CPU', max_length=12),
        ),
        migrations.AddField(
            model_name='cpucooler',
            name='type',
            field=models.CharField(default='CPUCooler', max_length=12),
        ),
        migrations.AddField(
            model_name='gpu',
            name='type',
            field=models.CharField(default='Storage', max_length=12),
        ),
        migrations.AddField(
            model_name='memory',
            name='type',
            field=models.CharField(default='Memory', max_length=12),
        ),
        migrations.AddField(
            model_name='powersupply',
            name='type',
            field=models.CharField(default='Storage', max_length=12),
        ),
        migrations.AddField(
            model_name='storage',
            name='type',
            field=models.CharField(default='Storage', max_length=12),
        ),
    ]
