# Generated by Django 4.1.2 on 2022-10-29 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_cpu_type_cpucooler_type_gpu_type_memory_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpu',
            name='type',
        ),
        migrations.RemoveField(
            model_name='cpucooler',
            name='type',
        ),
        migrations.RemoveField(
            model_name='gpu',
            name='type',
        ),
        migrations.RemoveField(
            model_name='memory',
            name='type',
        ),
        migrations.RemoveField(
            model_name='powersupply',
            name='type',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='type',
        ),
        migrations.AlterField(
            model_name='cpu',
            name='allData',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='CPU', to='web.alldata'),
        ),
        migrations.AlterField(
            model_name='memory',
            name='allData',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='memory', to='web.alldata'),
        ),
    ]
