# Generated by Django 4.1.2 on 2022-10-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_remove_userdata_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='outputcomputer',
            name='case',
            field=models.CharField(default='nothing', max_length=50),
        ),
        migrations.AddField(
            model_name='outputcomputer',
            name='case_p',
            field=models.FloatField(default=10),
        ),
        migrations.AddField(
            model_name='outputcomputer',
            name='cpu',
            field=models.CharField(default='nothing', max_length=50),
        ),
        migrations.AddField(
            model_name='outputcomputer',
            name='cpuCooler',
            field=models.CharField(default='nothing', max_length=50),
        ),
        migrations.AddField(
            model_name='outputcomputer',
            name='cpuCooler_p',
            field=models.FloatField(default=10),
        ),
        migrations.AddField(
            model_name='outputcomputer',
            name='cpu_p',
            field=models.FloatField(default=10),
        ),
        migrations.AddField(
            model_name='outputcomputer',
            name='gpu',
            field=models.CharField(default='nothing', max_length=50),
        ),
        migrations.AddField(
            model_name='outputcomputer',
            name='gpu_p',
            field=models.FloatField(default=10),
        ),
        migrations.AddField(
            model_name='outputcomputer',
            name='memory',
            field=models.CharField(default='nothing', max_length=50),
        ),
        migrations.AddField(
            model_name='outputcomputer',
            name='memory_p',
            field=models.FloatField(default=10),
        ),
        migrations.AddField(
            model_name='outputcomputer',
            name='motherboard',
            field=models.CharField(default='nothing', max_length=50),
        ),
        migrations.AddField(
            model_name='outputcomputer',
            name='motherboard_p',
            field=models.FloatField(default=10),
        ),
        migrations.AddField(
            model_name='outputcomputer',
            name='powerSupply',
            field=models.CharField(default='nothing', max_length=50),
        ),
        migrations.AddField(
            model_name='outputcomputer',
            name='powerSupply_p',
            field=models.FloatField(default=10),
        ),
        migrations.AddField(
            model_name='outputcomputer',
            name='storage',
            field=models.CharField(default='nothing', max_length=50),
        ),
        migrations.AddField(
            model_name='outputcomputer',
            name='storage_p',
            field=models.FloatField(default=10),
        ),
        migrations.AlterField(
            model_name='outputcomputer',
            name='total_price',
            field=models.FloatField(default=10, max_length=50),
        ),
    ]
