# Generated by Django 4.1.2 on 2022-10-30 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_outputcomputer_case_outputcomputer_case_p_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='gigs',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
