# Generated by Django 4.1.2 on 2022-10-30 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_cpucooler_alldata_alter_gpu_alldata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpu',
            name='coreClock',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='gpu',
            name='memory',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='memory',
            name='gigs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='powersupply',
            name='effiency',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='powersupply',
            name='watts',
            field=models.IntegerField(default=0),
        ),
    ]
