# Generated by Django 4.1.2 on 2022-10-30 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_gpu_coreclock_gpu_memory_memory_gigs_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cpu',
            old_name='performanceCoreClock',
            new_name='performanceBoostClock',
        ),
    ]
