# Generated by Django 4.1.2 on 2022-10-30 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_rename_performancecoreclock_cpu_performanceboostclock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cpu',
            old_name='performanceBoostClock',
            new_name='clockSpeed',
        ),
    ]
