# Generated by Django 4.1.2 on 2022-10-30 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_rename_performanceboostclock_cpu_clockspeed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storage',
            name='hardDrives',
        ),
    ]
