# Generated by Django 4.1.2 on 2022-10-30 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_remove_storage_harddrives'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='size',
            field=models.FloatField(default=0),
        ),
    ]
