# Generated by Django 4.1.2 on 2022-10-30 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_case_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='name',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='case',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='case',
            name='size',
            field=models.CharField(default='unknown', max_length=60),
        ),
    ]
