# Generated by Django 4.1.2 on 2022-10-30 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_alter_case_name_alter_case_price_alter_case_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='capacity',
            field=models.FloatField(default=0),
        ),
    ]
