# Generated by Django 4.1.2 on 2022-10-30 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_userdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='aesthetics',
            new_name='aesthetic',
        ),
    ]
