# Generated by Django 4.1.2 on 2022-10-30 12:38

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_rename_aesthetics_userdata_aesthetic'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='image_url',
            field=models.ImageField(blank=True, default='smile_face.jpeg', null=True, upload_to=web.models.upload_to),
        ),
    ]
